CREATE DATABASE IF NOT EXISTS auth_db;
USE auth_db;

CREATE TABLE users (
  user_id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) UNIQUE NOT NULL,
  role ENUM('ADMIN','INSTRUCTOR','STUDENT') NOT NULL,
  pass_hash VARCHAR(200) NOT NULL,
  status ENUM('ACTIVE','LOCKED') DEFAULT 'ACTIVE',
  last_login TIMESTAMP NULL
);


CREATE TABLE login_attempts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  success BOOLEAN,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);
